I'm sorry, but an uncaught exception occurred.

While running game code:
TypeError: 'RevertableList' object is not callable

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in script
    python hide:
  File "C:\Users\ManuelAlejandroChave\Downloads\renpy-8.2.3-sdk\renpy\ast.py", line 823, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "C:\Users\ManuelAlejandroChave\Downloads\renpy-8.2.3-sdk\renpy\python.py", line 1178, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/_layout/screen_main_menu.rpym", line 28, in <module>
    python hide:
  File "renpy/common/_layout/screen_main_menu.rpym", line 35, in _execute_python_hide
    ui.interact()
  File "C:\Users\ManuelAlejandroChave\Downloads\renpy-8.2.3-sdk\renpy\ui.py", line 301, in interact
    rv = renpy.game.interface.interact(roll_forward=roll_forward, **kwargs)
  File "C:\Users\ManuelAlejandroChave\Downloads\renpy-8.2.3-sdk\renpy\display\core.py", line 2166, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, pause_modal=pause_modal, **kwargs) # type: ignore
  File "C:\Users\ManuelAlejandroChave\Downloads\renpy-8.2.3-sdk\renpy\display\core.py", line 2609, in interact_core
    trans = instantiate_transition(None, old_root, layers_root)
  File "C:\Users\ManuelAlejandroChave\Downloads\renpy-8.2.3-sdk\renpy\display\core.py", line 2519, in instantiate_transition
    trans = self.ongoing_transition[layer](
TypeError: 'RevertableList' object is not callable

Windows-10-10.0.19045 AMD64
Ren'Py 8.2.3.24061702
Utopia 1.0
Sat Jul 20 07:04:13 2024
